config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :articles
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'services' => 'static_pages#services'

  get 'news' => 'static_pages#news'

  get 'visit' => 'static_pages#visit'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :articles, only: [:create, :destroy]
  
  resources :people, only: [:show]

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture, PictureUploader
    validates :title, presence: true
    validates :content, presence: true, length: { maximum: 1000 }
    validates :picture, presence: true, allow_blank: true
    validates :user_id, presence: true
    validate :picture_size
    
    def page(order = :id, per_page = 30)
      total = Article.count(order)
      position = total - id
      (position.to_f/per_page).ceil
    end
    
    private
    
    # Validates the size of an uploaded picture.
    def picture_size
        if picture.size > 5.megabytes
          errors.add(:picture, "should be less than 5MB")
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @users = User.all
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @user = current_user
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article created!"
      redirect_to news_url
    else
      @feed_items = []
      render 'new'
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    flash[:success] = "Article deleted"
    redirect_to request.referer || login_url
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :picture)
    end
    
    def correct_user
      @article = current_user.articles.find_by(id: params[:id])
      redirect_to login_url if @article.nil?
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="article">
<li id="article-<%= article.id %>">
  <%= link_to gravatar_for(article.user, size: 80), article.user %>
  <span class="user"><h2><%= link_to article.user.name, article.user %></h2></span>
  <span class="title"><h3>Title:</h3><p><%= article.title %></p></span>
  <span class="content"><h3>Content:</h3><p>
    <%= image_tag article.picture.url if article.picture? %>
    <%= simple_format(article.content) %>
    </p>
  </span>
  <span class="timestamp"><h3>Timestamp:</h3><p>
    Posted <%= time_ago_in_words(article.created_at) %> ago.</p>
  </span>
  <% if current_user?(article.user) %>
  <h3>
    <%= link_to "delete", article, method: :delete,
                                  data: { confirm: "You sure?" } %>
                                  </h3>
  <% end %>
</li></div>

app/views/articles/_form.html.erb
<section class="page" id="content">
  <h2>New Article</h2>
  <%= form_for(@article, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <div class="inputTitle">
        <p>
        <%= f.label :title, "Title:" %>
        </p>
        <p>
        <%= f.text_field :title %>
        </p>
      </div>
      <div class="inputContent">
        <p>
        <%= f.label :content, "Content:" %>
        </p>
        <p>
        <%= f.text_area :content, placeholder: "Compose new article" %>
        </p>
      </div>
      <div class="picture">
        <p>
        <%= f.label :picture, "Picture:" %>
        </p>
        <p>
        <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </p>
      </div>
      <div class="actions">
        <p>
        <%= f.submit "Post", id: "submit" %>
        </p>
      </div>
  <% end %>
</section>

<script type="text/javascript">
  $('#article_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Image url</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.image_url %></td>
        <td><%= article.user %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<% provide(:title, 'New article') %>
  <%= render 'form' %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @article.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>