config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :articles
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'services' => 'static_pages#services'

  get 'news' => 'static_pages#news'

  get 'visit' => 'static_pages#visit'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :articles, only: [:create, :destroy]
  
  resources :people, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    attr_accessor :remember_token, :activation_token, :reset_token
    before_save :downcase_email
    before_create :create_activation_digest
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }, allow_blank: true
    
    # Returns the hash digest of the given string.
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end
    
    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
    
    # Activates an account.
    def activate
        update_attribute(:activated, true)
        update_attribute(:activated_at, Time.zone.now)
    end
    
    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end
    
    # Sets the password reset attributes.
    def create_reset_digest
        self.reset_token = User.new_token
        update_attribute(:reset_digest, User.digest(reset_token))
        update_attribute(:reset_sent_at, Time.zone.now)
    end
    
    # Sends password reset email.
    def send_password_reset_email
        UserMailer.password_reset(self).deliver_now
    end
    
    # Returns true if a password reset has expired.
    def password_reset_expired?
        reset_sent_at < 2.hours.ago
    end
    
    # Defines a proto-feed.
    def feed
        Article.where("user_id = ?", id)
    end
    
    private
    
    # Converts email to all lower-case.
    def downcase_email
        self.email = email.downcase
    end
    
    # Creates and assigns the activation token and digest.
    def create_activation_digest
        self.activation_token = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def show
    @user = User.find(params[:id])
    if logged_in?
      @article = current_user.articles.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.all
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  # Before filters
  
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location 
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(login_url) unless current_user?(@user)
  end
  
  # Confirms an admin user.
  def admin_user
    redirect_to(login_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<section class="page" id="content">
  <div id="container">
    <h2>Update your profile</h2>
             <%= form_for(@user) do |f| %>
               <%= render 'shared/error_messages', object: f.object %>
                 <p>
                 <%= f.label :name, "Name:" %>
                 </p>
                 <p>
                 <%= f.text_field :name %>
                 </p>
                 <p>
                 <%= f.label :email, "Email:" %>
                 </p>
                 <p>
                 <%= f.email_field :email %>
                 </p>
                 <p>
                 <%= f.label :password, "Password:" %>
                 </p>
                 <p>
                 <%= f.password_field :password %>
                 </p>
                 <p>
                 <%= f.label :password_confirmation, "Confirmation:" %>
                 </p>
                 <p>
                 <%= f.password_field :password_confirmation %>
                 </p>
                 <p>
                 <%= f.submit "Save changes", id: "submit" %>
                 </p>
             <% end %>
             <div class="gravatar_edit">
                 <%= gravatar_for @user %>
                 <a href="http://gravatar.com/emails" target=_blank><h1>Change</h1></a>
             </div>
  </div>
</section>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<section class="page" id="content">
  <div id="container">
      <h2>All users</h2>
      <ul class="users">
          <% @users.each do |user| %>
            <li>
              <h1>
              <%= gravatar_for user, size: 80 %>
              <%= link_to user.name, user %>
              <% if current_user.admin? && !current_user?(user) %>
                | <%= link_to "delete", user, method: :delete, 
                                              data: { confirm: "You sure?" } %>
              <% end %>
              </h1>
            </li>
          <% end %>
      </ul>
  </div>
</section>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<section class="page" id="content">
      <div id="container">
          <h2>Sign up</h2>
             <%= form_for(@user) do |f| %>
               <%= render 'shared/error_messages', object: f.object %>
                 <p>
                 <%= f.label :name, "Name:" %>
                 </p>
                 <p>
                 <%= f.text_field :name %>
                 </p>
                 <p>
                 <%= f.label :email, "Email:" %>
                 </p>
                 <p>
                 <%= f.email_field :email %>
                 </p>
                 <p>
                 <%= f.label :password, "Password:" %>
                 </p>
                 <p>
                 <%= f.password_field :password %>
                 </p>
                 <p>
                 <%= f.label :password_confirmation, "Confirmation:" %>
                 </p>
                 <p>
                 <%= f.password_field :password_confirmation %>
                 </p>
                 <p>
                 <%= f.submit "Create my account", id: "submit" %>
                 </p>
             <% end %>
      </div>
</section>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<section class="page" id="content">
  <div id="container">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
      <ul>
      <% if logged_in? %>
        <li><%= link_to "Users", users_path, id: "usersMenu" %></li>
        <li><%= link_to "Settings", edit_user_path(current_user), id: "usersMenu" %></li>
        <li><%= link_to "Log out", logout_path, method: "delete", id: "usersMenu" %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
      </ul>
    </h1>
  </div>
</section>
<% if logged_in? %>
  <%= render 'articles/form' %>
  <%= render 'shared/feed' %>
<% end %>