config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :articles
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'services' => 'static_pages#services'

  get 'news' => 'static_pages#news'

  get 'visit' => 'static_pages#visit'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  
  post 'login' => 'sessions#create'
  
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :articles, only: [:create, :destroy]
  
  resources :people, only: [:show]

end

app/views/layouts/_footer.html.erb
<footer>
  <p>
    楊梅鶯地政士事務所<br>
    住址：台灣台中市西區三民路一段127巷10號<br>
    電話：(04)23713178<br>
    傳真：(04)23713179<br>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <h1><%= link_to "六象工商不動產顧問公司", root_path, id: "logo" %></h1>
    <nav>
      <ul>
        <li class="<%=is_active('home')%>"><%= link_to "首頁", root_path %></li>
        <li class="<%=is_active('about')%>"><%= link_to "專業團隊", about_path %></li>
        <li class="<%=is_active('services')%>"><%= link_to "服務", services_path %></li>
        <li class="<%=is_active('news')%>"><%= link_to "新聞", news_path %></li>
        <li class="<%=is_active('visit')%>"><%= link_to "拜訪", visit_path, 'data-no-turbolink' => true %></li>
        <li class="<%=is_active('contact')%>"><%= link_to "參考資料", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>        

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDaiHpfdztF_SN_O4UnOTPOPZlMiyp1JWI" type="text/javascript"></script>
    <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <h2><%= message %></h2>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>